version: '3.4'

services:
  app:
    image: gradle:5.6.1-jdk8
    entrypoint: /bin/sleep infinity
    working_dir: /usr/src/app
    volumes:
      - "../source/:/usr/src/app"
    user: root
    ports:
      - "8080"
    environment:
     - DNSDOCK_ALIAS=$DNSDOCK_ALIAS_MM
     - VIRTUAL_PORT=8080
     - VIRTUAL_HOST=$DNSDOCK_ALIAS_MM
